# Generated by Django 5.2.1 on 2025-07-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='signature',
        ),
    ]
