# Generated by Django 5.2.1 on 2025-07-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_signature'),
        ('signatures', '0007_remove_signature_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='signatures.signature'),
        ),
    ]
