# Generated by Django 5.2.1 on 2025-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='position_x',
            field=models.FloatField(default=0, help_text='签名在墙上的X坐标'),
        ),
        migrations.AddField(
            model_name='signature',
            name='position_y',
            field=models.FloatField(default=0, help_text='签名在墙上的Y坐标'),
        ),
        migrations.AddField(
            model_name='signature',
            name='rotation',
            field=models.IntegerField(default=0, help_text='签名的旋转角度(0-360)'),
        ),
        migrations.AddField(
            model_name='signature',
            name='scale',
            field=models.FloatField(default=1.0, help_text='签名的缩放比例'),
        ),
        migrations.AddField(
            model_name='signature',
            name='z_index',
            field=models.IntegerField(default=1, help_text='签名的层叠顺序'),
        ),
    ]
