# Generated by Django 5.2.1 on 2025-07-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_signature_position_x_signature_position_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(blank=True, help_text='上传您的手写签名或使用画布绘制', upload_to='signatures'),
        ),
    ]
