# Generated by Django 5.2.1 on 2025-07-06 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_alter_signature_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '签名墙',
                'verbose_name_plural': '签名墙',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='signature',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='signatures.signatureboard'),
        ),
    ]
