# Generated by Django 5.2.1 on 2025-07-06 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_signatureboard_signature_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='signatureboard',
            options={},
        ),
        migrations.RemoveField(
            model_name='signature',
            name='board',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='z_index',
        ),
        migrations.RemoveField(
            model_name='signatureboard',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='signature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(upload_to='signatures/', verbose_name='签名图片'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='signatureboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='signatureboard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_boards', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='signatureboard',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='signatureboard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.CreateModel(
            name='SignaturePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0, verbose_name='X坐标')),
                ('position_y', models.FloatField(default=0, verbose_name='Y坐标')),
                ('rotation', models.FloatField(default=0, verbose_name='旋转角度')),
                ('scale', models.FloatField(default=1.0, verbose_name='缩放比例')),
                ('z_index', models.IntegerField(default=1, verbose_name='层级')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否在墙上显示')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.signatureboard', verbose_name='签名墙')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.signature', verbose_name='签名')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('signature', 'board')},
            },
        ),
        migrations.AddField(
            model_name='signatureboard',
            name='signatures',
            field=models.ManyToManyField(related_name='boards', through='signatures.SignaturePlacement', to='signatures.signature', verbose_name='签名'),
        ),
    ]
