# Generated by Django 5.2.1 on 2025-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_signature'),
        ('signatures', '0005_alter_signature_options_alter_signatureboard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='related_signatures', to='blog.post', verbose_name='关联文章'),
        ),
    ]
