# Generated by Django 5.2.1 on 2025-07-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0006_signature_related_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='related_posts',
        ),
    ]
